Why Numpy??

* Its fast
* Behind the scenes optimizations written in C
* Vectorization via broadcasting (avoiding loos)
* Backbone of other Python sientific packages



### NumPy Data Types and Attributes

In [1]:
import numpy as np

## DataTypes & Attributes

In [5]:
# NumPy's main type is ndarray

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[1., 2.0, 3.3], 
              [4, 5, 6.5]])

a3 = np.array([[[1,2,3], 
                [4,5,6],
                [7,8,9]],
                [[10,11,12], 
                [13,14,15],
                [16,17,18]]])

In [15]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [16]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [17]:
a1.shape

(3,)

In [18]:
a2.shape

(2, 3)

In [19]:
a3.shape

(2, 3, 3)

In [21]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [22]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [23]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [24]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [26]:
### Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [29]:
import pandas as pd

df = pd.DataFrame(a1)
df

0
0  1
1  2
2  3

## Creating Numpy Arrays

In [30]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [31]:
sample_array.dtype

dtype('int32')

In [32]:
ones = np.ones((2,4))

In [33]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
ones.dtype

dtype('float64')

In [36]:
type(ones)

numpy.ndarray

In [37]:
zeros = np.zeros((3,3))

In [38]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
range_array = np.arange(0,10,2)

In [40]:
range_array

array([0, 2, 4, 6, 8])

In [42]:
random_array = np.random.randint(0,10,size = (3,5))

In [43]:
random_array

array([[8, 9, 1, 2, 1],
       [3, 2, 1, 9, 5],
       [1, 6, 5, 5, 8]])

In [44]:
random_array.size

15

In [45]:
random_array.shape

(3, 5)

In [46]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.88592806, 0.32181994, 0.37030837],
       [0.31909251, 0.22744914, 0.98881675],
       [0.45255769, 0.9596283 , 0.21764349],
       [0.22839373, 0.1391944 , 0.29544645],
       [0.48001362, 0.89630644, 0.78358204]])

In [47]:
random_array_2.shape

(5, 3)

In [49]:
random_array_3 = np.random.rand(5,3)

In [50]:
random_array_3

array([[0.43418102, 0.51355241, 0.20246783],
       [0.49197145, 0.19610095, 0.71532773],
       [0.53901556, 0.20434143, 0.21387862],
       [0.53748726, 0.70561181, 0.45513702],
       [0.13874825, 0.47989303, 0.46229352]])

In [51]:
# Pseudo-random numbers
np.random.seed()