Why Numpy??

* Its fast
* Behind the scenes optimizations written in C
* Vectorization via broadcasting (avoiding loos)
* Backbone of other Python sientific packages



### NumPy Data Types and Attributes

In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main type is ndarray

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1., 2.0, 3.3], 
              [4, 5, 6.5]])

a3 = np.array([[[1,2,3], 
                [4,5,6],
                [7,8,9]],
                [[10,11,12], 
                [13,14,15],
                [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
### Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [15]:
import pandas as pd

df = pd.DataFrame(a1)
df

0
0  1
1  2
2  3

## Creating Numpy Arrays

In [16]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2,4))

In [19]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeros = np.zeros((3,3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0,10,2)

In [25]:
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0,10,size = (3,5))

In [27]:
random_array

array([[0, 5, 7, 2, 6],
       [3, 8, 6, 3, 4],
       [2, 9, 9, 3, 8]])

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

In [30]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.32418688, 0.48800141, 0.80223063],
       [0.16775549, 0.75176051, 0.5477813 ],
       [0.91447554, 0.18986025, 0.98084059],
       [0.60539086, 0.49488289, 0.3420339 ],
       [0.17081979, 0.69906655, 0.1517387 ]])

In [31]:
random_array_2.shape

(5, 3)

In [32]:
random_array_3 = np.random.rand(5,3)

In [33]:
random_array_3

array([[0.63023372, 0.63624203, 0.07705834],
       [0.19513757, 0.33109142, 0.18864278],
       [0.06274507, 0.97044189, 0.2247478 ],
       [0.84786799, 0.22872311, 0.46513426],
       [0.56566845, 0.27108398, 0.45163788]])

In [35]:
random_array = np.random.randint(0,10,size = (3,5))
random_array

array([[1, 4, 9, 8, 9],
       [1, 1, 3, 7, 4],
       [5, 6, 5, 7, 2]])

In [37]:
random_array = np.random.rand(3,5)
random_array

array([[0.82456046, 0.36901896, 0.37957185, 0.93130957, 0.93467041],
       [0.70926043, 0.70709351, 0.17589309, 0.07519489, 0.74226234],
       [0.6440201 , 0.1251405 , 0.35553316, 0.55066736, 0.61098572]])

In [39]:
random_array = np.random.random((3,5))
random_array

array([[0.52002407, 0.43379549, 0.71621226, 0.22259811, 0.03727243],
       [0.04719253, 0.19608634, 0.45477371, 0.6311667 , 0.16507548],
       [0.07391265, 0.11997355, 0.21636469, 0.65838728, 0.28657117]])