Why Numpy??

* Its fast
* Behind the scenes optimizations written in C
* Vectorization via broadcasting (avoiding loos)
* Backbone of other Python sientific packages



### NumPy Data Types and Attributes

In [1]:
import numpy as np

## DataTypes & Attributes

In [5]:
# NumPy's main type is ndarray

a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[1., 2.0, 3.3], 
              [4, 5, 6.5]])

a3 = np.array([[[1,2,3], 
                [4,5,6],
                [7,8,9]],
                [[10,11,12], 
                [13,14,15],
                [16,17,18]]])

In [15]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [16]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])